fullnameOverride: devoops-rating-service
replicaCount: 1

image:
  registry: docker.io
  repository: threeamigoscoding/devoops-rating-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 8080
  grpc:
    enabled: false

ingress:
  enabled: false

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 1000m

health:
  path: /actuator/health
  periodSeconds: 10
  failureThreshold: 3
  startup:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 60

configData:
  JAVA_TOOL_OPTIONS: "-XX:+UseSerialGC -Xms128m -Xmx384m -XX:ActiveProcessorCount=1"
  SERVER_PORT: "8080"
  LOGSTASH_HOST: "devoops-logstash:5000"
  ZIPKIN_HOST: "devoops-jaeger"
  ZIPKIN_PORT: "9411"
  MONGODB_HOST: "devoops-mongodb"
  MONGODB_PORT: "27017"

secretData:
  MONGODB_USERNAME: "devoops"
  MONGODB_PASSWORD: "devoops"
